apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "v1.19.4"
    helm:
      values: |
        crds:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  # Disable autosync, as Argo CD instances will manually sync after testing
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
