apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-envs
spec:
  project: default
  source:
    targetRevision: "#{Octopus.Action[Run a Script].Package[cert-manager].PackageVersion}"